FROM python:3

# Set the working dir
WORKDIR /usr/src/app

# Copy in the req file
COPY requirements.txt .

# Install before adding code so cache is not invalidated
RUN pip3 install -r requirements.txt

# Copy in the code
COPY . .